AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Parameters:
  StageName:
    Type: String
  CicdBucket:
    Type: String
Resources:
  DefaultApi:
    Type: AWS::Serverless::Api
    Properties:
      GatewayResponses:
        BAD_REQUEST_BODY:
          ResponseTemplates:
            application/json: '{ "message": "$context.error.validationErrorString"}'
      StageName: live
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location:
              Fn::Sub: s3://${CicdBucket}/spec/api-spec.yaml
    Metadata:
      SamResourceId: DefaultApi
  SignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.handler.signup
      Runtime: python3.7
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: DefaultApi
            Path: /users/signup
            Method: POST
      CodeUri: s3://s3-eu-west-1-cicd-awesomecms/0f2501ebbae540ce2276941ee742623c
    Metadata:
      SamResourceId: SignUpFunction
  ConfirmedSignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.handler.confirm_signup
      Runtime: python3.7
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: DefaultApi
            Path: /users/confirmeAccount
            Method: POST
      CodeUri: s3://s3-eu-west-1-cicd-awesomecms/0f2501ebbae540ce2276941ee742623c
    Metadata:
      SamResourceId: ConfirmedSignUpFunction
  SignInFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.handler.signin
      Runtime: python3.7
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: DefaultApi
            Path: /users/signin
            Method: POST
      CodeUri: s3://s3-eu-west-1-cicd-awesomecms/0f2501ebbae540ce2276941ee742623c
    Metadata:
      SamResourceId: SignInFunction
  CreateArticleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.handler.create_article
      Runtime: python3.7
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: ArticleTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: DefaultApi
            Path: /articles
            Method: POST
      Environment:
        Variables:
          TABLE_NAME:
            Ref: ArticleTable
      CodeUri: s3://s3-eu-west-1-cicd-awesomecms/0f2501ebbae540ce2276941ee742623c
    Metadata:
      SamResourceId: CreateArticleFunction
  FindArticlesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.handler.find_articles
      Runtime: python3.7
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: ArticleTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: DefaultApi
            Path: /articles
            Method: GET
      Environment:
        Variables:
          TABLE_NAME:
            Ref: ArticleTable
      CodeUri: s3://s3-eu-west-1-cicd-awesomecms/0f2501ebbae540ce2276941ee742623c
    Metadata:
      SamResourceId: FindArticlesFunction
  DeleteArticleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.handler.delete_article
      Runtime: python3.7
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: ArticleTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: DefaultApi
            Path: /articles/{article_id}
            Method: DELETE
      Environment:
        Variables:
          TABLE_NAME:
            Ref: ArticleTable
      CodeUri: s3://s3-eu-west-1-cicd-awesomecms/0f2501ebbae540ce2276941ee742623c
    Metadata:
      SamResourceId: DeleteArticleFunction
  ArticleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: awesomecms-${StageName}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: author
        AttributeType: S
      - AttributeName: date
        AttributeType: S
      - AttributeName: title
        AttributeType: S
      KeySchema:
      - AttributeName: author
        KeyType: HASH
      - AttributeName: title
        KeyType: RANGE
      LocalSecondaryIndexes:
      - IndexName: author-date
        KeySchema:
        - AttributeName: author
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      GlobalSecondaryIndexes:
      - IndexName: uuid
        KeySchema:
        - AttributeName: uuid
          KeyType: HASH
        Projection:
          ProjectionType: ALL
    Metadata:
      SamResourceId: ArticleTable
